export const ALL_PRODUCT = "ALL_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER    = "LOGIN_USER"


