
export const SET_PRODUCT = "SET_PRODUCT"
export const AFTER_ADD_PRODUCT = "AFTER_ADD_PRODUCT"
export const AFTER_UPDATE_PRODUCT = "AFTER_UPDATE_PRODUCT"
export const AFTER_DELETE_PRODUCT = "AFTER_DELETE_PRODUCT"






