
export const SET_ACCOUNT = "SET_ACCOUNT"
export const AFTER_ADD_ACCOUNT = "AFTER_ADD_ACCOUNT"
export const AFTER_UPDATE_ACCOUNT = "AFTER_UPDATE_ACCOUNT"
export const AFTER_DELETE_ACCOUNT = "AFTER_DELETE_ACCOUNT"






